---
- name: Install required packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - vim
    - zip

- name: Verify installations
  command: "{{ item }} --version"
  register: version_check
  changed_when: false
  loop:
    - vim
    - zip
  
- name: Display installed versions
  debug:
    var: version_check.results
